etcd:
  address:
  - http://localhost:2379
logger:
  level: debug
server:
  name: core
  app_id: core 
  sources:
    - kafka://139.198.125.147:9092/core4/core
    - kafka://139.198.125.147:9092/core5/core
    - kafka://139.198.125.147:9092/core6/core
    - kafka://139.198.125.147:9092/core7/core
proxy:
  name: core1
  http_port: 20029
  grpc_port: 20030
components:
  store:
    name: noop
    properties:
      - key: store_name
        value: core-state

dispatcher:
  id: dispatcher1
  enabled: true
  name: dispatcher
  downstreams:
    - kafka://139.198.125.147:9092/core0/core
    - kafka://139.198.125.147:9092/core1/core
    - kafka://139.198.125.147:9092/core2/core
    - kafka://139.198.125.147:9092/core3/core
    - kafka://139.198.125.147:9092/core4/core
    - kafka://139.198.125.147:9092/core5/core
    - kafka://139.198.125.147:9092/core6/core
    - kafka://139.198.125.147:9092/core7/core