etcd:
  address:
  - http://tkeel-middleware-etcd-0:2379
logger:
  level: debug
server:
  name: core
  app_id: core 
  sources:
    - kafka://tkeel-middleware-kafka:9092/core4/core
    - kafka://tkeel-middleware-kafka:9092/core5/core
    - kafka://tkeel-middleware-kafka:9092/core6/core
    - kafka://tkeel-middleware-kafka:9092/core7/core
components:
  store:
    name: noop
    properties:
      - key: store_name
        value: core-state

dispatcher:
  id: dispatcher
  enabled: true
  name: dispatcher
  downstreams:
    - kafka://tkeel-middleware-kafka:9092/core0/core
    - kafka://tkeel-middleware-kafka:9092/core1/core
    - kafka://tkeel-middleware-kafka:9092/core2/core
    - kafka://tkeel-middleware-kafka:9092/core3/core
    - kafka://tkeel-middleware-kafka:9092/core4/core
    - kafka://tkeel-middleware-kafka:9092/core5/core
    - kafka://tkeel-middleware-kafka:9092/core6/core
    - kafka://tkeel-middleware-kafka:9092/core7/core