apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: core-pubsub-cluster1
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: redisDB
    value: 4
scopes:
  - core
